// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Filename = require("bs-platform/lib/js/filename.js");

var $slash = Filename.concat;

exports.$slash = $slash;
/* Filename Not a pure module */
