parameters:
  platform: "macOS"
  vmImage: "macOS-10.13"
  STAGING_DIRECTORY: /Users/vsts/STAGING
  STAGING_DIRECTORY_UNIX: /Users/vsts/STAGING
  ESY__CACHE_INSTALL_PATH: /Users/vsts/.esy/3____________________________________________________________________/i
  ESY__CACHE_SOURCE_TARBALL_PATH: /Users/vsts/.esy/source/i

jobs:
  - job: ${{ parameters.platform }}
    pool:
      vmImage: ${{ parameters.vmImage }}
      demands: node.js
    timeoutInMinutes: 120 # This is mostly for Windows
    variables:
      STAGING_DIRECTORY: ${{ parameters.STAGING_DIRECTORY }}
      STAGING_DIRECTORY_UNIX: ${{ parameters.STAGING_DIRECTORY_UNIX }}
      ESY__CACHE_INSTALL_PATH: ${{ parameters.ESY__CACHE_INSTALL_PATH }}
      ESY__CACHE_SOURCE_TARBALL_PATH: ${{ parameters.ESY__CACHE_SOURCE_TARBALL_PATH }}

    steps:
      - template: utils/use-node.yml
      - template: utils/use-esy.yml
      - template: utils/restore-build-cache.yml
      - script: "esy install"
        displayName: "esy install"
      - script: "esy build"
        displayName: "esy build"
      - script: "esy npm-release"
        displayName: "esy npm-release"
      - script: "npm install"
        displayName: "npm install"
        workingDirectory: "npm-cli"
      - script: "npm build"
        displayName: "Building pesy npm cli (bsb)"
        workingDirectory: "npm-cli"
      - ${{ if eq(parameters.platform, 'Windows') }}:
          - script: "npm i -g esy-bash"
            displayName: 'Install esy-bash (for e2e)'
      - script: "npm run rollup"
        displayName: "Building pesy npm cli (bundling)"
        workingDirectory: "npm-cli"
      - ${{ if eq(parameters.platform, 'Windows') }}:
          - script: .\_build\install\default\bin\Runner.exe
            displayName: 'Running e2e tests'
      - ${{ if ne(parameters.platform, 'Windows') }}:
          - script: ./_build/install/default/bin/Runner.exe
            displayName: 'Running e2e tests'
            env:
              OCAMLRUNPARAM: 'b'
      - template: utils/publish-build-cache.yml
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: ${{ parameters.platform }}"
        inputs:
          PathtoPublish: "_release"
          ArtifactName: ${{ parameters.platform }}
