// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Filename = require('bs-platform/lib/js/filename.js');

var $slash = Filename.concat;

exports.$slash = $slash;
/* No side effect */
